#!/bin/bash
#SBATCH --job-name=22-PSS-MPI
#SBATCH --partition normal
#SBATCH --nodes=1 --ntasks-per-node=40
#SBATCH --time=30:00
#SBATCH --chdir=.

module load intel 

rm -f res1152_mpi
for p in 1 2 3 4 6 8 10 12 16 20 24 32 36 ; do
    mpirun -n $p ./MPI-build/mvm 1152 100 >> res1152_mpi
done

rm -f res9216_mpi
for p in 1 2 3 4 6 8 10 12 16 20 24 32 36 ; do
    mpirun -n $p ./MPI-build/mvm 9216 100 >> res9216_mpi
done
