#!/bin/bash
#SBATCH --job-name=22-PSS-OMP
#SBATCH --partition normal
#SBATCH --nodes=1 --ntasks-per-node=40
#SBATCH --time=30:00
#SBATCH --chdir=.

module load intel

rm -f res1152_omp
for p in 1 2 3 4 6 8 10 12 16 20 24 32 36 ; do ## x20core
    export OMP_NUM_THREADS=$p ; ./OMP-build/mvm 1152 100 >> res1152_omp
done

rm -f res9216_omp
for p in 1 2 3 4 6 8 10 12 16 20 24 32 36 ; do ## x20core
    export OMP_NUM_THREADS=$p ; ./OMP-build/mvm 9216 100 >> res9216_omp
done
